version: "3.1"

services:
  followers:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: "followers-server"
    hostname: "followers-server"
    #Mapping ports
    ports:
      # <port_on_local>:<port_in_machine>
      - 8082:8082
    #Will be accessible through os.Getenv("PORT")
    environment:
      - PORT=8082
      # NoSQL: environment variable holding connection URI for Neo4J database
      # Local DB instance
      - NEO4J_DB=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASS=NekaSifra
    depends_on:
      neo4j:
        condition: service_healthy

  # NoSQL: Neo4J DB
  neo4j:
    image: neo4j
    restart: always
    ports:
      # bolt
      - "7687:7687"
      # http
      - "7474:7474"
      # https
      - "7473:7473"
    # Docker healtcheck - checks if database is "alive"
    # test: [ "CMD-SHELL", "echo RETURN 1 | cypher-shell -a <NEO4J_dbms_connector_bolt_listen__address> -u <user defined username> -p <user defined password> || exit 1" ]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo RETURN 1 | cypher-shell -a bolt://neo4j:7687 -u neo4j -p NekaSifra || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      - NEO4J_AUTH=neo4j/NekaSifra
    volumes:
    - followers-data:/data
    - ./init-scripts:/docker-entrypoint-initdb.d # Mounting init-scripts directory

volumes:
  followers-data:
